config/routes.rb
HostingApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => "pages#home"

end

app/views/layouts/_footer.html.haml
%footer
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href => "http://news.bainrnd.com/"} News

app/views/layouts/_header.html.haml
%header
  %h1.latin Bain RnD Inc

app/views/layouts/_side.html.haml
%ul#nav.aside
  %li= link_to "Home", root_path
  - if signed_in?
    %li= link_to "Users", users_path
    %li= link_to "Profile", current_user
    %li= link_to "Settings", edit_user_path(current_user)
  %li= link_to "Help", help_path
  - if signed_in?
    %li= link_to "Sign out", signout_path, :method => :delete
  - else
    %li= link_to "Sign in", signin_path

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print.css', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/custom.css', :media => 'screen'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = csrf_meta_tag
    = render 'layouts/stylesheets'
    /= javascript_include_tag :defaults
    / For some reason :defaults fails?
    = javascript_include_tag 
  %body
    = render 'layouts/header'
    #wrapper
      = render 'layouts/side'
      #subwrap.round
        - flash.each do |key, value|
          = content_tag(:div, value, :class => "flash #{key}")
        = yield
        = debug(params) if Rails.env.development?
    = render 'layouts/footer'